language: c
compiler: gcc
before_script:
    - sudo apt-get build-dep -qq xchat
    - sudo apt-get install -qq libnotify-dev libproxy-dev libpci-dev libcanberra-dev monodevelop
script: 
    - ./autogen.sh
    - ./configure --enable-textfe --with-theme-manager
    - make
notifications:
    irc:
        channels: "chat.freenode.net#hexchat-devel"
        template: "Build #%{build_number} (%{commit}) by %{author}: %{message}"
        on_success: change
