language: c
compiler: clang
before_script:
    - sudo apt-get update
    - sudo apt-get build-dep -qq xchat
    - sudo apt-get install -qq libnotify-dev libproxy-dev libpci-dev libcanberra-dev monodevelop intltool
script: 
    - ./autogen.sh --enable-textfe --with-theme-manager --enable-static-analysis
    - make V=1 -j$(nproc)
notifications:
    irc:
        channels: "chat.freenode.net#hexchat-devel"
        template: "Build %{build_url} (%{commit} in %{branch}) by %{author}: %{message}"
        on_success: change
matrix:
     fast_finish: true
