language: c
compiler:
    - gcc
    - clang
before_script:
    - sudo apt-get update
    - sudo apt-get build-dep -qq xchat
    - sudo apt-get install -qq libnotify-dev libproxy-dev libpci-dev libcanberra-dev monodevelop gnome-common
script: 
    - ./autogen.sh
    - ./configure --enable-textfe --with-theme-manager
    - make V=1 -j$(nproc)
notifications:
    irc:
        channels: "chat.freenode.net#hexchat-devel"
        template: "Build #%{build_number} (%{commit}) by %{author}: %{message}"
        on_success: change
matrix:
     fast_finish: true
